### PR TITLE
A few assorted changes, including e1m7 and mgdm3 support

### PR DESCRIPTION
**Pull request by ceeeKay**
Rebased/separated out into a few themed commits. mapdb.json is actually not in the source files at present- only the release files, so I've added my current/complete version here at the end.

### CODE REVIEW

**Comment by ceeeKay** [comment]
Use https://github.com/jpiolho/QECTF/pull/3 instead

**Comment by jpiolho** [comment]
Before merging, just want to clarify and confirm with you that, once merged, your maps & modifications can be modified by me or anyone else that contributes. There's also always possibility of stuff being removed in the future. I will try to make sure credits remain in place though :)

I just don't want to create false guarantees or expectations by merging into here and would advise people that want to remain in full control of their creation to instead maintain a separate fork.

Is all of this ok for you?
(I'll probably be copying some form of this text into a merge guideline document for this project and my other ones)

**Comment by jpiolho** [comment]
Ah, another thing I forgot to mention. For future PRs, separate things into different PRs instead of commits because I use squash merging which means every commit will be merged into 1. So for example in this case I'd consider these different PRs: e1m7, mgdm3, teamplay 2, entmod doc, mapdb.json.

But I'm ok with merging this one as it is. I've never done much open source before so I'm trying to get used to it 😅

**Comment by ceeeKay** [comment]
> Before merging, just want to clarify and confirm with you that, once merged, your maps & modifications can be modified by me or anyone else that contributes. There's also always possibility of stuff being removed in the future. I will try to make sure credits remain in place though :)

Yep I'm ok with this. I don't really want to maintain a fork long-term and if I do further additions/tweaks I'm happy to let you opt (or not) to take those contributions. Same goes for other folks if they want to make improvements on what I've started.

> For future PRs, separate things into different PRs

Noted :) I haven't really done a lot of github stuff, so the PR process is new to me. I didn't realize the PR merge would squash (or would by default). Happy to separate them out if you'd prefer, merging all together is up to you :)

Thanks!!

**Pull request merged**
